export const skills = [
  { name: 'React.js', pct: 95, color: 'accent' },
  { name: 'Next.js', pct: 90, color: 'accent' },
  { name: 'TypeScript', pct: 85, color: 'accent2' },
  { name: 'Tailwind CSS', pct: 92, color: 'accent' },
  { name: 'React Native', pct: 80, color: 'accent2' },
  { name: 'WebSocket / Pusher', pct: 75, color: 'accent3' },
]

export const projects = [
  {
    id: '01',
    slug: 'queue-management-system',
    label: 'Latest · 2024–2025',
    badge: true,
    category: 'Featured',
    title: 'Queue Management System',
    desc: 'Real-time multi-app monorepo for clinic & hospital queue management. Three frontend apps — Admin Dashboard, User Portal kiosk, and TV Display — with live updates and integrated thermal printer.',
    tags: [
      { label: 'React.js', color: 'green' },
      { label: 'Vite', color: 'green' },
      { label: 'Pusher.js', color: 'blue' },
      { label: 'WebSocket', color: 'blue' },
      { label: 'Turborepo', color: '' },
      { label: 'Kiosk · Android', color: 'pink' },
      { label: 'Thermal Printer', color: '' },
    ],
    features: [
      { text: '3 apps: Admin Dashboard · User Portal · TV Display', color: '' },
      { text: 'Real-time queue via Pusher.js + Laravel Echo', color: 'blue' },
      { text: 'Kiosk lockdown mode (Device Owner + Lock Task)', color: 'pink' },
    ],
    visual: 'qms',
    featured: true,
    details: {
      role: 'Lead Frontend Developer',
      duration: '2024 - 2025',
      team: '3 developers',
      overview: 'A comprehensive real-time queue management system designed for clinics and hospitals. The project consists of three interconnected frontend applications managed as a Turborepo monorepo — an Admin Dashboard for staff, a User Portal kiosk for patients, and a TV Display for waiting rooms.',
      highlights: [
        'Built a monorepo architecture using Turborepo with shared packages for UI components, API clients, and TypeScript configs across 3 apps.',
        'Implemented real-time queue updates using Pusher.js and Laravel Echo, ensuring all three apps stay synchronized with sub-second latency.',
        'Developed Android kiosk lockdown mode using Device Owner API and Lock Task Mode for secure, unattended patient-facing terminals.',
        'Integrated thermal printer support (ESC/POS) for automatic queue ticket printing directly from the browser.',
        'Designed responsive admin dashboard with live queue management, analytics, and multi-counter support.',
      ],
      stack: ['React.js', 'Vite', 'Turborepo', 'Pusher.js', 'Laravel Echo', 'Tailwind CSS', 'ESC/POS', 'Android WebView'],
    },
  },
  {
    id: '02',
    slug: 'user-feedback-app',
    label: 'Freelance',
    badge: false,
    category: '',
    title: 'User Feedback App',
    desc: 'Kiosk-mode React Native app for capturing post-service feedback. Full-screen lockdown with multi-step rating form and auto-reset between sessions.',
    tags: [
      { label: 'React Native', color: 'pink' },
      { label: 'Kiosk Mode', color: 'pink' },
      { label: 'Expo', color: 'green' },
      { label: 'Android', color: 'blue' },
      { label: 'Multi-step Form', color: '' },
    ],
    features: [
      { text: 'Full-screen kiosk lockdown', color: 'pink' },
      { text: 'Star rating + free-text feedback', color: '' },
      { text: 'Auto-reset after submission', color: 'blue' },
    ],
    visual: 'phone',
    featured: false,
    details: {
      role: 'Freelance Developer',
      duration: '2024',
      team: 'Solo',
      overview: 'A kiosk-mode React Native application designed for capturing post-service user feedback in clinics and service centers. The app runs in full-screen lockdown mode on dedicated Android tablets, presenting a multi-step rating form that auto-resets between sessions.',
      highlights: [
        'Implemented full-screen kiosk lockdown preventing users from exiting the app or accessing system settings.',
        'Built a multi-step feedback flow with star rating, category selection, and free-text input.',
        'Auto-reset mechanism clears all form data after submission and returns to the welcome screen.',
        'Offline-first architecture queues feedback submissions when network is unavailable.',
        'Optimized for continuous 24/7 operation on low-end Android tablets.',
      ],
      stack: ['React Native', 'Expo', 'Android Kiosk Mode', 'AsyncStorage', 'REST API'],
    },
  },
  {
    id: '03',
    slug: 'ina-go-id',
    label: 'PT Salt Indonesia',
    badge: false,
    category: '',
    title: 'INA.go.id',
    desc: 'Official government portal built with Next.js. Focus on accessibility, performance optimization, and pixel-perfect responsive layout across devices.',
    tags: [
      { label: 'Next.js', color: 'green' },
      { label: 'TypeScript', color: 'blue' },
      { label: 'A11y', color: 'pink' },
      { label: 'Gov Portal', color: '' },
      { label: 'SSR', color: 'green' },
    ],
    features: [
      { text: 'Accessibility-first (WCAG standards)', color: 'blue' },
      { text: 'SSR + performance optimization', color: '' },
      { text: 'Responsive across all breakpoints', color: 'pink' },
    ],
    visual: 'gov',
    featured: false,
    details: {
      role: 'Frontend Developer',
      duration: '2023 - 2024',
      team: 'PT Salt Indonesia',
      overview: 'Official Indonesian government portal (INA.go.id) built with Next.js. The project focused heavily on accessibility compliance (WCAG standards), server-side rendering for SEO and performance, and pixel-perfect responsive layouts across all device sizes.',
      highlights: [
        'Implemented WCAG 2.1 AA accessibility standards including keyboard navigation, screen reader support, and proper ARIA attributes.',
        'Leveraged Next.js SSR and ISR for optimal page load performance and SEO on a high-traffic government site.',
        'Built pixel-perfect responsive layouts matching Figma designs across mobile, tablet, and desktop breakpoints.',
        'Optimized Core Web Vitals (LCP, FID, CLS) achieving consistently high Lighthouse scores.',
        'Collaborated with backend team on REST API integration for dynamic content management.',
      ],
      stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'SSR/ISR', 'WCAG 2.1', 'REST API'],
    },
  },
  {
    id: '04',
    slug: 'daya-id',
    label: 'PT Salt Indonesia',
    badge: false,
    category: '',
    title: 'Daya.id',
    desc: 'Analytics dashboard system for UMKM empowerment platform. Complex JS modules covering date-range filtering, Chart.js visualizations, and multi-section API integration.',
    tags: [
      { label: 'JavaScript', color: 'pink' },
      { label: 'Chart.js', color: 'pink' },
      { label: 'Pimcore / PHP', color: '' },
      { label: 'REST API', color: 'blue' },
      { label: 'Date Filtering', color: '' },
    ],
    features: [
      { text: '6 report modules (Tanya Ahli, Pelatihan, dll)', color: 'pink' },
      { text: 'Dynamic date-range filter + Chart.js', color: '' },
      { text: 'Multi-endpoint API integration', color: 'blue' },
    ],
    visual: 'daya',
    featured: false,
    details: {
      role: 'Frontend Developer',
      duration: '2023',
      team: 'PT Salt Indonesia',
      overview: 'Analytics dashboard system for Daya.id, an UMKM (SME) empowerment platform by Bank Danamon. Built complex JavaScript modules covering 6 report sections with date-range filtering, Chart.js visualizations, and multi-endpoint API integration.',
      highlights: [
        'Developed 6 independent report modules (Tanya Ahli, Pelatihan, Produk, etc.) each with unique data visualizations.',
        'Implemented dynamic date-range filtering with custom calendar picker and preset ranges.',
        'Integrated Chart.js for bar charts, line graphs, and doughnut charts with responsive sizing.',
        'Built multi-endpoint API integration layer handling concurrent requests and data transformation.',
        'Optimized rendering performance for large datasets with virtualization and memoization.',
      ],
      stack: ['JavaScript', 'Chart.js', 'Pimcore/PHP', 'REST API', 'CSS3', 'Date-fns'],
    },
  },
  {
    id: '05',
    slug: 'umkmall-id',
    label: 'PT Salt Indonesia',
    badge: false,
    category: '',
    title: 'UMKMall.id',
    desc: 'E-commerce platform for Indonesian SMEs with SSR, dynamic product catalog, and mobile-first responsive layout.',
    tags: [
      { label: 'Next.js', color: 'green' },
      { label: 'TypeScript', color: 'blue' },
      { label: 'SSR', color: '' },
      { label: 'Tailwind', color: 'green' },
    ],
    features: [
      { text: 'SSR + dynamic product catalog', color: '' },
      { text: 'Mobile-first responsive layout', color: 'blue' },
    ],
    visual: 'shop',
    featured: false,
    details: {
      role: 'Frontend Developer',
      duration: '2023',
      team: 'PT Salt Indonesia',
      overview: 'E-commerce platform for Indonesian SMEs (UMKMall.id) enabling small businesses to showcase and sell products online. Built with Next.js for SSR, featuring a dynamic product catalog, search functionality, and mobile-first responsive design.',
      highlights: [
        'Built SSR product pages for optimal SEO and fast initial page loads on slow connections.',
        'Implemented dynamic product catalog with filtering, sorting, and category navigation.',
        'Designed mobile-first responsive layout ensuring seamless experience across all devices.',
        'Integrated product search with debounced API calls and instant result previews.',
        'Developed reusable e-commerce UI components (product cards, cart summary, checkout flow).',
      ],
      stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'SSR', 'REST API', 'Zustand'],
    },
  },
  {
    id: '06',
    slug: 'tv-queue-display',
    label: 'Part of QMS',
    badge: false,
    category: '',
    title: 'TV Queue Display',
    desc: 'Real-time fullscreen TV display for clinic waiting rooms. Live queue numbers via WebSocket, optimized for large screens.',
    tags: [
      { label: 'React.js', color: 'green' },
      { label: 'WebSocket', color: 'blue' },
      { label: 'Vite', color: 'green' },
      { label: 'Fullscreen', color: '' },
    ],
    features: [
      { text: 'Live updates via Pusher.js', color: 'blue' },
      { text: 'Optimized for TV / large display', color: '' },
    ],
    visual: 'tv',
    featured: false,
    details: {
      role: 'Frontend Developer',
      duration: '2024 - 2025',
      team: '3 developers',
      overview: 'Real-time fullscreen TV display application for clinic and hospital waiting rooms. Part of the Queue Management System, this app shows live queue numbers, counter assignments, and status updates via WebSocket, optimized for large-screen TVs.',
      highlights: [
        'Designed fullscreen TV-optimized UI with large, readable typography for waiting room visibility.',
        'Implemented real-time queue updates via Pusher.js WebSocket with automatic reconnection handling.',
        'Built animated queue number transitions with smooth enter/exit animations for each update.',
        'Auto-scaling layout that adapts to different TV resolutions (720p, 1080p, 4K).',
        'Zero-interaction design — app runs autonomously with no manual input required.',
      ],
      stack: ['React.js', 'Vite', 'Pusher.js', 'WebSocket', 'CSS Animations', 'Fullscreen API'],
    },
  },
]

export const stats = [
  { num: '3+', label: 'Years exp.', color: 'accent' },
  { num: '12+', label: 'Projects done', color: 'accent2' },
  { num: '5★', label: 'Upwork rating', color: 'accent3' },
  { num: '5', label: 'Industries', color: 'accent' },
]

export const industryData = [
  { label: 'Fintech · 40%', color: '#c8f060' },
  { label: 'SaaS / Gov · 25%', color: '#60d4f0' },
  { label: 'Edtech · 15%', color: '#f060a0' },
  { label: 'Others · 20%', color: '#2a2a28' },
]

export const toolData = [
  { label: 'React', pct: 95, color: '#c8f060' },
  { label: 'Next.js', pct: 90, color: '#c8f060' },
  { label: 'Tailwind', pct: 92, color: '#60d4f0' },
  { label: 'R. Native', pct: 80, color: '#60d4f0' },
  { label: 'TypeScript', pct: 85, color: '#f060a0' },
]
